### PR TITLE
Go-Client remoting and RocketMqClient common method implement

### PR DESCRIPTION
**Pull request by StyleTang**
Go-Client remoting and RocketMqClient common method implement

### CODE REVIEW

**Comment by StyleTang** [comment]
I had discuss the implement of remoting package with @wenfengwang 
The PR can be merged, please review.

**Comment by wenfengwang** [comment]
LGTM

**Comment by kimmking** [comment]
hi, guys, I want to know whether every subproject here have already been assigned to a special conrtibutor,
such as dotnet-client, mongodb.
if i want to join the team, how can i submit my application, thanks so much.

**Comment by dongeforever** [comment]
@kimmking As I know, each subproject has one or more contributors who mainly contribute to it.  Anyway, the Apache Community welcome any contribution, you could just submit PRs to begin your contribution.

**Comment by kimmking** [comment]
@dongeforever  thanks a lot.
I am interesting in several modules, rocketmq-jms, dotnetclient,nodejs client, camel-rocketmq  etc.

**Pull request closed without merging**
