### PR TITLE
[ROCKETMQ-193] init subproject: rocketmq-redis replicator 

### PR DESCRIPTION
**Pull request by Zhang-Ke**

### CODE REVIEW

**Comment by ranqiqiang** [comment]
这项目 直接 pull 下来不能编译额、、、

**Comment by Zhang-Ke** [comment]
I think it's no problem to run "maven clean install -DskipTest". If you want to run "test" phase, please refer to "CONTRIBUTING.md".

**Comment by ranqiqiang** [comment]
RocketMqUtils 是scala 的  ，我单独 想使用rocketmq-spark 这个工程  编译不过，scala  是不是 一定要STB 打包编译 才行？

**Comment by vongosling** [comment]
@Zhang-Ke Could you remove author info and follow our codestyle, such as add license. if have any question, please let me know :-)

**Comment by Zhang-Ke** [comment]
Please see #29 instead, and this PR was discarded.

**Comment by vongosling** [comment]
@Zhang-Ke Thanks, It is really good practice when discarded deserted pr.

**Pull request closed without merging**
