### PR TITLE
[ROCKETMQ-268]add rocketmq-cpp code

### PR DESCRIPTION
**Pull request by vincentWangKB**
add rocketmq-cpp code

### CODE REVIEW

**Comment by lizhanhui** [comment]
Trying to create a CMakeLists.txt on top of this PR, but it looks there is something missing: 
```cpp
MetaqJson::Value json
```
I grepped MetaqJson in the code, but no definition of this struct if found. Please double check the code is compilable.

**Comment by lizhanhui** [comment]
A second issue about alog, there are only header files and binary static lib file, where is source code for the static lib files?

**Comment by lizhanhui** [comment]
About the disruptor module in src/thread, copyright declarations of this module files are different. Is the source code copied from somewhere? If so, is its license compatible with Apache Software Foundation?

**Comment by lizhanhui** [comment]
Many useless files are included, for example in project folder.  Can we remove them?

**Comment by lizhanhui** [comment]
As it's now part of the Apache RocketMQ project, IMO, rocketmq namespace should be used instead of metaq.

**Comment by vincentWangKB** [comment]
For build and install, cmake and Makefile are all supported on linux platform now. Thanks

**Comment by vincentWangKB** [comment]
@lizhanhui all build issue had been fixed, please pull latest code, thanks

**Comment by lizhanhui** [comment]
Yes,  I see your update...Thanks for you contribution. CMake, IMO, is very good to have!

One more thing, I think we can assume  dependent libraries are all installed in the standard default way, thus, we can use find_package features and developers do not have to modify CMake build file.  If required libraries are missing, we just abort in the cmake phase.

**Comment by vincentWangKB** [comment]
@lizhanhui alog lib had been instead by boost::log, thanks your advisement

**Comment by vesense** [comment]
I suggest that we'd better squash the commits before merging a PR.

**Comment by lizhanhui** [comment]
@vesense Yes, we will do this before actually merging

**Comment by lizhanhui** [comment]
@vincentWangKB Another issue with the code, currently all classes sit in the namespace of metaq, we should rename it to rocketmq.

**Comment by lizhanhui** [comment]
@vincentWangKB Any progress? It's been a while since last update to this PR.

**Comment by lizhanhui** [comment]
Maybe, we can merge it and create JIRA tickets to polish the code. Any idea?

**Comment by vincentWangKB** [comment]
@lizhanhui namespace had been changed to rocketmq, thanks

**Comment by lizhanhui** [comment]
Though there are still quite a few unused files, I am fine to merge this PR first and fix issues later on.

**Comment by lizhanhui** [comment]
This patch looks good enough to be merged.  Thanks @vincentWangKB

**Comment by lizhanhui** [comment]
This Pull Request has been merged and it's safe to close this PR. @vincentWangKB

**Comment by vongosling** [comment]
It is a good practice for apache way :-)

**Comment by XadillaX** [comment]
Consider removing boost? This dependency is too large for a SDK not a complete project.

**Comment by vincentWangKB** [comment]
close pull request, as rocketmq cpp code had been merged

**Pull request closed without merging**
