### PR TITLE
Go-Client's implement

### PR DESCRIPTION
**Pull request by StyleTang**
All features of milestone 1 has been completed

Detail Design: https://github.com/apache/incubator-rocketmq-externals/pull/19

# RoadMap-Milestone1

## Consumer
- [x] ConsumerType
    - [x] PushConsumer
- [x] MessageListener
    - [x] Concurrently
- [x] MessageModel
    - [x] CLUSTERING
- [x] OffsetStore
    - [x] RemoteBrokerOffsetStore
- [x] RebalanceService
- [x] PullMessageService
- [x] ConsumeMessageService
- [x] AllocateMessageQueueStrategy
    - [x] AllocateMessageQueueAveragely
- [x] Other
    - [x] Config
    - [x] ZIP
    - [x] ConsumeFromWhere
        - [x] CONSUME_FROM_LAST_OFFSET
        - [x] CONSUME_FROM_FIRST_OFFSET
        - [x] CONSUME_FROM_TIMESTAMP
    - [x] Retry(sendMessageBack)
    - [x] TimeOut(clearExpiredMessage)
    - [x] ACK(partSuccess)
    - [x] FlowControl(messageCanNotConsume)
    
## Producer
- [x] ProducerType
    - [x] DefaultProducer
- [x] API
    - [x] Send
        - [x] Sync
- [x] Other
    - [x] DelayMessage
    - [x] Config
    - [x] MessageId Generate
    - [x] CompressMsg
    - [x] TimeOut
    - [x] LoadBalance
    - [x] DefaultTopic
    - [x] VipChannel
    - [x] MQFaultStrategy

## Manager
- [x] Controller
    - [x] PullMessageController
- [x] Task
    - [x] UpdateTopicRouteInfo
    - [x] Heartbeat
    - [x] Rebalance
    - [x] PullMessage
    - [x] CleanExpireMsg
- [x] ClientRemotingProcessor
    - [x] CHECK_TRANSACTION_STATE
    - [x] NOTIFY_CONSUMER_IDS_CHANGED
    - [x] RESET_CONSUMER_CLIENT_OFFSET
    - [x] GET_CONSUMER_STATUS_FROM_CLIENT
    - [x] GET_CONSUMER_RUNNING_INFO
    - [x] CONSUME_MESSAGE_DIRECTLY

## Remoting
- [x] MqClientRequest
    - [x] InvokeSync
    - [x] InvokeAsync
    - [x] InvokeOneWay
- [x] Serialize
    - [x] JSON
    - [x] ROCKETMQ
- [x] NamesrvAddrChoosed(HA)

go-client-producer
go-client-consumer
go-client-consumer-detail
go-client-consumer-detail-2

### CODE REVIEW

**Comment by StyleTang** [comment]
To Be Done
- [ ] Integration Testing(There is no Integration Testing)
- [ ] Clean Code(Some code needs to be refactored )

**Comment by wenfengwang** [comment]
Cool~The PR looks good to me. Because the personal things are more recently, I'm so sorry that i don't have much free time to contribute. Thanks @StyleTang.

**Comment by lindzh** [comment]
+1

**Comment by wenfengwang** [comment]
Can this PR be merged? I would like to do some optimization and add tests based on this PR. Thanks~

**Pull request closed without merging**
