### PR TITLE
[ROCKETMQ-171] Initialized the PHP_SDK basic structure

### PR DESCRIPTION
**Pull request by netroby**
See https://issues.apache.org/jira/browse/ROCKETMQ-171
for tracking

### CODE REVIEW

**Comment by vesense** [comment]
@netroby Seems like all the files are missing apache license header.

**Comment by netroby** [comment]
OK, I am working on it.

**Comment by netroby** [comment]
@vesense had add headers

**Comment by dongeforever** [comment]
@netroby This PR has been merged. If any new PR is submitted, please notice me.

**Comment by jokechat** [comment]
```
Class 'RocketMQ\Client\Latency\LatencyFaultToleranceImpl' not found
```

what ? how to do ?

**Pull request closed without merging**
