### PR TITLE
[ROCKETMQ-170]Rename README.txt to README.md; Add windows support

### PR DESCRIPTION
**Pull request by netroby**

### CODE REVIEW

**Comment by vsair** [comment]
I have test on windows 7(installed docker toolbox 1.11.1), the result is:

1. Should run _docker-machine_ first, it will tell you set some envs.
```
SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.99.100:2376
SET DOCKER_CERT_PATH=C:\Users\xigu.lx\.docker\machine\machines\default
SET DOCKER_MACHINE_NAME=default
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('docker-machine.exe env default') DO @%i
```
2. Then run the _docker_build.cmd_
3. Then run the _docker_run.cmd_

I think you could add the first step(auto config the env) to cmd, maybe!

Thanks.

**Comment by netroby** [comment]
how to setup docker may a bit out of topic




On Sat, Apr 1, 2017 at 5:18 PM +0800, "Eric Liu" <notifications@github.com> wrote:












I have test on windows 7(installed docker toolbox 1.11.1), the result is:

Should run docker-machine first, it will tell you set some envs.

SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.99.100:2376
SET DOCKER_CERT_PATH=C:\Users\xigu.lx\.docker\machine\machines\default
SET DOCKER_MACHINE_NAME=default
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('docker-machine.exe env default') DO @%i


Then run the docker_build.cmd
Then run the docker_run.cmd



I think you could add the first step(auto config the env) to cmd, maybe!


Thanks.

**Comment by dongeforever** [comment]
@vsair @netroby Yeah. how to setup docker env is not the major work here.

**Comment by dongeforever** [comment]
@netroby I want to merge this PR. Could you please provide your email address that could be identified as your github account ?

**Comment by netroby** [comment]
hufeng1987@gmail.com




On Mon, Apr 3, 2017 at 10:06 PM +0800, "zander" <notifications@github.com> wrote:












@netroby I want to merge this PR. Could you please provide your email address that could be identified as your github account ?

**Comment by vongosling** [comment]
@netroby i think you are familiar with rocketmq PR process. Could you modify your PR topic and make association with Jira isssue?Now ,you can not point up the component~

**Comment by netroby** [comment]
Sorry, but no rocketmq-docker component.

**Comment by dongeforever** [comment]
@vongosling @zhouxinyu please help add the component 'rocketmq-externals' or 'rocketmq-docker'

**Comment by netroby** [comment]
@dongeforever @vongosling @zhouxinyu 
I had made a jira issue . and changed PR title/commit log
https://issues.apache.org/jira/browse/ROCKETMQ-170

**Comment by dongeforever** [comment]
@netroby nice. I would merge this PR

**Comment by netroby** [comment]
Thanks for your time

**Pull request closed without merging**
