### PR TITLE
[ROCKETMQ-81] import rocketmq plugin for spark streaming

### PR DESCRIPTION
**Pull request by hustfxj**
This plugin is for spark streaming based on pull mode. And you can see READ.ME for more details. And we will add more tests for this plugin after that.

### CODE REVIEW

**Comment by vongosling** [comment]
@dongeforever @shroman @stevenschew thoughts?

**Comment by ranqiqiang** [comment]
感谢  ~。~ 这个东西 能正式使用了吗？ 期待

**Comment by shroman** [comment]
@vongosling There are two PRs for ROCKETMQ-81. I guess @hustfxj or @vesense will have to compile them in one, and they recheck it together :)

Guys, please make sure you assign JIRA issues to yourselves before you start working on tasks, and update them. For instance, @hustfxj if you are working on the issue, please change the status, so @vesense knows you are working on it and doesn't waste his time. Two pull requests are submitted but the issue has still "Open" status :D

In fact, I think it's pretty common to pick the issue and work on it if there is no progress on it for a long time.

**Comment by zhouxinyu** [comment]
Agree with @shroman .
But this two PRs are different implementations, based on PUSH and PULL models respectively, may be both can coexist.

**Comment by shroman** [comment]
@zhouxinyu yes, luckily they are :)
IMO, if the difference is just PUSH and PULL models, it's reasonable to merge them and improve. Any other ideas?

**Comment by vesense** [comment]
I plan to merge these two PRs into one. @hustfxj What do you think about it?

**Comment by hustfxj** [comment]
@vesense  It's great!  thank you

**Comment by zhouxinyu** [comment]
@vesense How much the merge progress has been made now?

**Comment by vesense** [comment]
@zhouxinyu Almost complete. I will submit it in this week. Some delay due to my computer wasn't working in the past few days. :smile:

**Comment by zhouxinyu** [comment]
@vesense Thanks for your efforts~  😄

**Comment by vesense** [comment]
I have completed the merging. The PR after merged is here: https://github.com/apache/incubator-rocketmq-externals/pull/4. Now I think we can merge it initially.
The following is the change:
* merge PR #5 to #4 
* fix the jdk version to 1.8
* fix package path
* merge common configs to java/org.apache.rocketmq.spark.RocketMQConfig
* merge common utils to scala/org.apache.rocketmq.spark.RocketMqUtils
* add RocketMQServerMock to improve testing
* improve document

 Thanks.

**Pull request closed without merging**
